// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeSckzPsSaCbCvs4BoH2KVmTFugJeZjVk',
    appId: '1:164790489552:web:2453ffeb8535c8d347a9d5',
    messagingSenderId: '164790489552',
    projectId: 'sample-go-router',
    authDomain: 'sample-go-router.firebaseapp.com',
    storageBucket: 'sample-go-router.firebasestorage.app',
    measurementId: 'G-P1232XYRTJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAob7jK_XvyCd5peoX5Fwb8Gug3WJ24Tlw',
    appId: '1:164790489552:android:454f40b54cafca9b47a9d5',
    messagingSenderId: '164790489552',
    projectId: 'sample-go-router',
    storageBucket: 'sample-go-router.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_VQZ2NHCoVLbIGI9mKpybpJPtxlLulJY',
    appId: '1:164790489552:ios:8cbbb01358848f8847a9d5',
    messagingSenderId: '164790489552',
    projectId: 'sample-go-router',
    storageBucket: 'sample-go-router.firebasestorage.app',
    iosBundleId: 'com.example.sampleGoRouter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_VQZ2NHCoVLbIGI9mKpybpJPtxlLulJY',
    appId: '1:164790489552:ios:8cbbb01358848f8847a9d5',
    messagingSenderId: '164790489552',
    projectId: 'sample-go-router',
    storageBucket: 'sample-go-router.firebasestorage.app',
    iosBundleId: 'com.example.sampleGoRouter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeSckzPsSaCbCvs4BoH2KVmTFugJeZjVk',
    appId: '1:164790489552:web:c59b22e7449f092947a9d5',
    messagingSenderId: '164790489552',
    projectId: 'sample-go-router',
    authDomain: 'sample-go-router.firebaseapp.com',
    storageBucket: 'sample-go-router.firebasestorage.app',
    measurementId: 'G-95ZN2R1YKZ',
  );
}
